### ISSUE TITLE
Cant't use on 500Hz

### ISSUE THREAD

**Issue by grryf** [Plasmatree/PID-Analyzer#32]
Hi,
I have PWM ESC so I can only 500Hz. All flights even 8 minutes long are "462848B < 500000B".
Logging with 1kHz makes an Exception.
Best Regards,
Radek

c:\Users\IT\Downloads\PID Analyzer>PID-Analyzer_0.52.exe -l C:\Users\IT\Documents\BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838.BBL
INFO 2018-06-30 21:01:41,533 PID-Analyzer_0.52.py:982: Decoding with 'c:\\Users\\IT\\Downloads\\PID Analyzer\\Blackbox_decode.exe'
INFO 2018-06-30 21:01:41,533 PID-Analyzer_0.52.py:984: PID-Analyzer 0.52
INFO 2018-06-30 21:01:41,533 PID-Analyzer_0.52.py:985: Hello Pilot!
WARNING 2018-06-30 21:01:41,562 PID-Analyzer_0.52.py:933: Ignoring BBL session 'C:\\Users\\IT\\Documents\\tmp\\BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838_temp0.BBL', 61B < 500000B.
Decoding log 'C:\Users\IT\Documents\tmp\BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838_temp1.BBL' to 'C:\Users\IT\Documents\tmp\BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838_temp1.01.csv'...

Log 1 of 1, start 01:07.604, end 11:02.274, duration 09:54.669

Statistics
Looptime           2047 avg            7.3 std dev (0.4%)
I frames    1135   46.3 bytes avg    52557 bytes total
P frames   35159   29.7 bytes avg  1043498 bytes total
E frames       2    9.0 bytes avg       18 bytes total
S frames      10    7.2 bytes avg       72 bytes total
Frames     36294   30.2 bytes avg  1096055 bytes total
Data rate   61Hz   1847 bytes/s      18500 baud

2 frames failed to decode, rendering 3 loop iterations unreadable. 1 iterations are missing in total (2ms, 0.00%)
254058 loop iterations weren't logged because of your blackbox_rate settings (520333ms, 87.50%)

Decoding log 'C:\Users\IT\Documents\tmp\BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838_temp2.BBL' to 'C:\Users\IT\Documents\tmp\BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838_temp2.01.csv'...

Log 1 of 1, start 00:36.045, end 10:45.835, duration 10:09.790

Statistics
Looptime           2047 avg            7.2 std dev (0.4%)
I frames    1163   46.6 bytes avg    54187 bytes total
P frames   36038   29.6 bytes avg  1065853 bytes total
E frames       2    9.0 bytes avg       18 bytes total
S frames      10    7.2 bytes avg       72 bytes total
Frames     37201   30.1 bytes avg  1120040 bytes total
Data rate   61Hz   1841 bytes/s      18500 baud

2 frames failed to decode, rendering 14 loop iterations unreadable. 13 iterations are missing in total (26ms, 0.00%)
260491 loop iterations weren't logged because of your blackbox_rate settings (533564ms, 87.50%)

INFO 2018-06-30 21:01:43,894 PID-Analyzer_0.52.py:676: Reading: Log 0
INFO 2018-06-30 21:01:44,154 PID-Analyzer_0.52.py:356: Processing:
INFO 2018-06-30 21:01:44,154 PID-Analyzer_0.52.py:671: roll...
Traceback (most recent call last):
  File "PID-Analyzer_0.52.py", line 989, in <module>
  File "PID-Analyzer_0.52.py", line 939, in run_analysis
  File "PID-Analyzer_0.52.py", line 781, in __init__
  File "PID-Analyzer_0.52.py", line 798, in _csv_iter
  File "PID-Analyzer_0.52.py", line 358, in __init__
  File "PID-Analyzer_0.52.py", line 672, in __analyze
  File "PID-Analyzer_0.52.py", line 63, in __init__
  File "PID-Analyzer_0.52.py", line 209, in winstacker
ValueError: setting an array element with a sequence.
Failed to execute script PID-Analyzer_0.52

c:\Users\IT\Downloads\PID Analyzer>C:\Users\IT\Documents\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404.BBL

c:\Users\IT\Downloads\PID Analyzer>PID-Analyzer_0.52.exe -l C:\Users\IT\Documents\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404.BBL
INFO 2018-06-30 21:02:54,144 PID-Analyzer_0.52.py:982: Decoding with 'c:\\Users\\IT\\Downloads\\PID Analyzer\\Blackbox_decode.exe'
INFO 2018-06-30 21:02:54,144 PID-Analyzer_0.52.py:984: PID-Analyzer 0.52
INFO 2018-06-30 21:02:54,144 PID-Analyzer_0.52.py:985: Hello Pilot!
WARNING 2018-06-30 21:02:54,209 PID-Analyzer_0.52.py:933: Ignoring BBL session 'C:\\Users\\IT\\Documents\\tmp\\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404_temp0.BBL', 61B < 500000B.
WARNING 2018-06-30 21:02:54,209 PID-Analyzer_0.52.py:933: Ignoring BBL session 'C:\\Users\\IT\\Documents\\tmp\\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404_temp1.BBL', 462848B < 500000B.
WARNING 2018-06-30 21:02:54,209 PID-Analyzer_0.52.py:933: Ignoring BBL session 'C:\\Users\\IT\\Documents\\tmp\\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404_temp2.BBL', 421888B < 500000B.
WARNING 2018-06-30 21:02:54,209 PID-Analyzer_0.52.py:933: Ignoring BBL session 'C:\\Users\\IT\\Documents\\tmp\\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404_temp3.BBL', 372736B < 500000B.
WARNING 2018-06-30 21:02:54,213 PID-Analyzer_0.52.py:933: Ignoring BBL session 'C:\\Users\\IT\\Documents\\tmp\\BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404_temp4.BBL', 315904B < 500000B.
INFO 2018-06-30 21:02:54,213 PID-Analyzer_0.52.py:940: Analysis complete, showing plot. (Close plot to exit.)

c:\Users\IT\Downloads\PID Analyzer>

**Comment by Plasmatree** [comment]
Can you post the log?

**Comment by grryf** [comment]
500Hz logging - too small:
[BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404.zip](https://github.com/Plasmatree/PID-Analyzer/files/2153043/BTTR_BLACKBOX_LOG_iFlight_281_20180630_145404.zip)

1000Hz logging - exception:
[BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838.zip](https://github.com/Plasmatree/PID-Analyzer/files/2153048/BTTR_BLACKBOX_LOG_iFlight_281_20180630_205838.zip)
