### ISSUE TITLE
Unable to analyze file (Blackbox app read it)

### ISSUE THREAD

**Issue by vinz486** [Plasmatree/PID-Analyzer#40]
Hi,
I have this output:
`vinz@xpvinz:~/bin/PID-Analyzer$ ./PID-Analyzer.py --blackbox_decode blackbox_decode -l BTFL_BLACKBOX_LOG_Diatone_20180805_121933.BBL -n test
INFO 2018-08-05 12:50:01,809 PID-Analyzer.py:982: Decoding with '/home/vinz/bin/PID-Analyzer/blackbox_decode'
INFO 2018-08-05 12:50:01,809 PID-Analyzer.py:984: PID-Analyzer 0.52
INFO 2018-08-05 12:50:01,809 PID-Analyzer.py:985: Hello Pilot!
WARNING 2018-08-05 12:50:01,824 PID-Analyzer.py:933: Ignoring BBL session '/home/vinz/bin/PID-Analyzer/test/BTFL_BLACKBOX_LOG_Diatone_20180805_121933_temp0.BBL', 61B < 500000B.
Decoding log '/home/vinz/bin/PID-Analyzer/test/BTFL_BLACKBOX_LOG_Diatone_20180805_121933_temp1.BBL' to '/home/vinz/bin/PID-Analyzer/test/BTFL_BLACKBOX_LOG_Diatone_20180805_121933_temp1.01.csv'...

Log 1 of 1, start 00:12.799, end 00:53.980, duration 00:41.181

Statistics
Looptime            508 avg           64.5 std dev (12.7%)
I frames    1246   39.2 bytes avg    48848 bytes total
P frames   78415   20.5 bytes avg  1610954 bytes total
E frames       2    9.0 bytes avg       18 bytes total
S frames       6    4.0 bytes avg       24 bytes total
Frames     79661   20.8 bytes avg  1659802 bytes total
Data rate 1934Hz  40394 bytes/s     404000 baud

1 frames failed to decode, rendering 44 loop iterations unreadable. 239084 iterations are missing in total (30889ms, 75.01%)

Decoding log '/home/vinz/bin/PID-Analyzer/test/BTFL_BLACKBOX_LOG_Diatone_20180805_121933_temp2.BBL' to '/home/vinz/bin/PID-Analyzer/test/BTFL_BLACKBOX_LOG_Diatone_20180805_121933_temp2.01.csv'...

Log 1 of 1, start 02:23.620, end 02:56.491, duration 00:32.871

Statistics
Looptime            509 avg           64.7 std dev (12.7%)
I frames     992   39.5 bytes avg    39170 bytes total
P frames   62462   20.6 bytes avg  1287746 bytes total
E frames       2    9.0 bytes avg       18 bytes total
S frames       5    4.0 bytes avg       20 bytes total
Frames     63454   20.9 bytes avg  1326916 bytes total
Data rate 1930Hz  40464 bytes/s     404700 baud

1 frames failed to decode, rendering 20 loop iterations unreadable. 190292 iterations are missing in total (24650ms, 74.99%)

INFO 2018-08-05 12:50:02,870 PID-Analyzer.py:676: Reading: Log 0
Traceback (most recent call last):
  File "./PID-Analyzer.py", line 989, in <module>
    run_analysis(clean_path(log_path), args.name, args.blackbox_decode, args.show, args.noise_bounds)
  File "./PID-Analyzer.py", line 939, in run_analysis
    test = BB_log(log_file_path, plot_name, blackbox_decode, show, noise_bounds)
  File "./PID-Analyzer.py", line 781, in __init__
    self.figs = self._csv_iter(self.heads)
  File "./PID-Analyzer.py", line 798, in _csv_iter
    analysed = CSV_log(h['tempFile'][:-3]+'01.csv', self.name, h, self.noise_bounds)
  File "./PID-Analyzer.py", line 354, in __init__
    self.data = self.readcsv(self.file)
  File "./PID-Analyzer.py", line 692, in readcsv
    data = read_csv(fpath, header=0, skipinitialspace=1, usecols=lambda k: k in wanted, dtype=np.float64)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 275, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 590, in __init__
    self._make_engine(self.engine)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 731, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1103, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 412, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3796)
TypeError: 'function' object is not iterable
`
Log contains 2 seessions: 1 in angle and 1 in acro, recorded at 2khz on Betaflight 3.4.1.

If I open the log with blackbox app I see the data and all it's ok.

[BTFL_BLACKBOX_LOG_Diatone_20180805_121933.BBL.zip](https://github.com/Plasmatree/PID-Analyzer/files/2260243/BTFL_BLACKBOX_LOG_Diatone_20180805_121933.BBL.zip)

Thank you for this interesting project and for your help!

**Comment by vinz486** [comment]
Hi,
solved.

On Ubuntu LTS 16.04 python defaults to version 2.7. To make it working must be ran using python3 explicit:

pyhton3 PID-Analyzer.py ....

(maybe this tip should be noted on README, ubuntu section)

Thanks anyway.
